### ISSUE TITLE
Transition to important locality filter to read from WOF property

### ISSUE THREAD

**Issue by nvkelso** [pelias/wof-pip-service#40]
In the earlier PR https://github.com/pelias/wof-pip-service/pull/36 less significant neighbourhoods were excluded from hierarchy label generation to remove labels for tiny rural neighbourhoods. But that filter is too aggressive (it limited label generation to only NYC, SF and a handful of mega cities globally) and hard codes the logic versus being data driven per feature.

To enable this logic to be data driven, WOF has added (https://github.com/whosonfirst/whosonfirst-data/issues/341) a boolean `mz:hierarchy_label` to all administrative records, not just neighbourhoods (the Pelias logic should extend to all placetypes, not just neighbourhoods).

For less important neighbourhoods (locality tiers 1, 2, 3) we've set the boolean to be `0` for false (values of `1` should be included in the label generation), via https://github.com/whosonfirst/whosonfirst-data/issues/342. We looked at also hiding this for mid-tier (4, 5) localities in https://github.com/whosonfirst/whosonfirst-data/issues/341 but most of those are actually interesting, especially outside the USA. 

If any more neighbourhoods should be excluded, please file issues against Who's On First Data for that parent locality.

**Comment by orangejulius** [comment]
Our acceptance tests caught some neighborhoods disappearing after #36 that we didn't want. We also found some on our own. They are:

* [Greenwhich Village](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=40.72956&point.lon=-73.994) ([spelunker](https://whosonfirst.mapzen.com/spelunker/id/420529189/#15/40.7314/-73.9968))
* [Midtown South](http://pelias.github.io/compare/#/v1/search%3Ftext=starbucks%2010010) ([spelunker](https://whosonfirst.mapzen.com/spelunker/id/85865701/#16/40.7414/-73.9894))
* [Kelburn](http://pelias.github.io/compare/#/v1/place%3Fids=openaddresses:address:nz/countrywide:405132) ([spelunker](https://whosonfirst.mapzen.com/spelunker/id/85772991/#15/-41.2866/174.7664))

All of these have mz:hierarchy_label set to 1, so #41 will resolve them. I'm sure there will be some that are missed, but we'll file issues in WOF for those as they arise.

**Comment by orangejulius** [comment]
This was done in #41!

**Comment by orangejulius** [comment]
This has now made it out into production (as of a few weeks ago actually)!
