### ISSUE TITLE
Log an error message if a layer's meta file cannot be found

### ISSUE THREAD

**Issue by orangejulius** [pelias/wof-pip-service#89]
Currently, if there is no data at all, including meta file, for a particular layer (for example some of the ones we have recently added such as `empire`), the pip service will load other layers, and then hang indefinitely while waiting for the layers with missing data to load. No message of any kind indicating that the layer data was missing is printed, so its quite hard to tell what went wrong.

**Comment by missinglink** [comment]
:+1: "Fail Early, Fail Loudly"

**Comment by trescube** [comment]
This project has been deprecated.  Do you mean for this to be in pelias-wof-admin-lookup?

**Comment by orangejulius** [comment]
oh woops. yes i did!
